language: python
python:
  - 3.5

env:
  - DJANGO=2.0

addons:
  postgresql: "9.4"
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
services:
  - postgresql

install:
  - pip install -r requirements.txt

script:
  - python manage.py test

before_script:
  - sqlite3 --version
  - psql -c 'create database testdb;' -U postgres
